
@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}

###
GET {{host}}/api/courses HTTP/1.1

###
GET {{host}}/api/courses/15 HTTP/1.1

###
POST {{host}}/api/courses HTTP/1.1
content-type: application/json

{
    "name": "sa"
}